"""add notes table

Revision ID: 04ad9941b0dc
Revises: 9ccd99dcd2aa
Create Date: 2025-11-30 11:23:31.899856

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "04ad9941b0dc"
down_revision: Union[str, Sequence[str], None] = "9ccd99dcd2aa"
branch_labels: Union[str, Sequence[str], None] = ("note",)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "note",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["usertable.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_note_title"), "note", ["title"], unique=False)
    op.create_index(op.f("ix_note_user_id"), "note", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_note_user_id"), table_name="note")
    op.drop_index(op.f("ix_note_title"), table_name="note")
    op.drop_table("note")
    # ### end Alembic commands ###
