"""add events,expenses

Revision ID: 3109c8c01810
Revises: 3336aa921d61
Create Date: 2025-12-19 09:35:56.058965

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3109c8c01810'
down_revision: Union[str, Sequence[str], None] = '3336aa921d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('events', 'end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('expenses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('expenses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('expenses', 'expense_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_foreign_key(None, 'expenses', 'usertable', ['user_id'], ['id'])
    op.create_foreign_key(None, 'expenses', 'expenses_categories', ['category_id'], ['id'])
    op.alter_column('expenses_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('expenses_categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('expenses_categories', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_constraint(op.f('expenses_categories_name_user_key'), 'expenses_categories', type_='unique')
    op.create_index(op.f('ix_expenses_categories_name'), 'expenses_categories', ['name'], unique=False)
    op.drop_constraint(op.f('expenses_categories_user_id_fkey'), 'expenses_categories', type_='foreignkey')
    op.create_foreign_key(None, 'expenses_categories', 'usertable', ['user_id'], ['id'])
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(length=2000),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(length=2000),
               nullable=True)
    op.drop_constraint(None, 'expenses_categories', type_='foreignkey')
    op.create_foreign_key(op.f('expenses_categories_user_id_fkey'), 'expenses_categories', 'usertable', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_expenses_categories_name'), table_name='expenses_categories')
    op.create_unique_constraint(op.f('expenses_categories_name_user_key'), 'expenses_categories', ['name', 'user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('expenses_categories', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('expenses_categories', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('expenses_categories', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.alter_column('expenses', 'expense_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('expenses', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('expenses', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('events', 'end_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('events', 'start_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###
