"""extract_base_model

Revision ID: 9ccd99dcd2aa
Revises: 590086b59ce4
Create Date: 2025-11-28 09:07:00.122767

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "9ccd99dcd2aa"
down_revision: Union[str, Sequence[str], None] = "590086b59ce4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usertable", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("usertable", sa.Column("updated_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usertable", "updated_at")
    op.drop_column("usertable", "created_at")
    # ### end Alembic commands ###
