from fastapi.security import OAuth2PasswordBearer

SCOPES: dict[str, str] = {
    "events:read": "Чтение событий",
    "events:create": "Создание событий",
    "events:update": "Обновление событий",
    "events:delete": "Удаление событий",
    "users:read": "Чтение списка пользователей и их данных",
    "users:create": "Создание пользователей",
    "me:read": "Чтение собственных данных пользователя",
    "tasks:read": "Чтение задач",
    "tasks:create": "Создание задач",
    "tasks:delete": "Удаление задач",
    "tasks:update": "Обновление задач",
    "note:create": "Создание пользователем заметки",
    "note:update": "Обновление заметки пользователем",
    "note:delete": "Удаление заметки пользователем",
    "note:read": "Чтение заметок",
    "expenses:read": "Чтение расходов",
    "expenses:create": "Создание расходов",
    "expenses:update": "Изменение расходов",
    "expenses:delete": "Удаление расходов",
    "expense_categories:read": "Чтение категорий расходов",
    "expense_categories:create": "Создание категорий расходов",
    "expense_categories:update": "изменение категорий расходов",
    "expense_categories:delete": "удаление категорий расходов",
}

ROLES_TO_SCOPES = {
    "administrator": list(SCOPES.keys()),
    "user": [
        "me:read",
        "events:read",
        "events:create",
        "events:update",
        "events:delete",
        "note:create",
        "note:update",
        "note:delete",
        "note:read",
        "tasks:read",
        "tasks:create",
        "tasks:update",
        "tasks:delete",
        "expenses:read",
        "expenses:create",
        "expenses:update",
        "expenses:delete",
        "expense_categories:read",
        "expense_categories:create",
        "expense_categories:update",
        "expense_categories:delete",
    ],
}
oauth2_scheme = OAuth2PasswordBearer(
    tokenUrl="/api/v1/auth/token",
    scopes=SCOPES,
)
